import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button } from 'antd';
import { ProCard } from '@ant-design/pro-components';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.tsx</code>
          </p>
          <ProCard title="默认尺寸" extra="extra" tooltip="这是提示" style={{ maxWidth: 300 }} headerBordered>
            <div>1 Card content</div>
            <div>Card content</div>
            <div>Card content</div>
          </ProCard>
          <ProCard
            title="小尺寸卡片"
            extra="extra"
            tooltip="这是提示"
            style={{ maxWidth: 300, marginBlockStart: 24 }}
            size="small"
          >
            <div>Card content</div>
            <div>Card content</div>
            <div>Card content</div>
          </ProCard>
        </div>
        <Button type="primary">Button</Button>
      </main>
    </>
  )
}
