version: "3.3"
services:
  biiboom_etl:
    #    build: .
    image: hk-biiboom-etl:latest
    container_name: biiboom-etl
    platform: linux/amd64
    restart: always
    networks:
      - biiboom
    environment:
      TZ: 'Asia/Shanghai'
      http_proxy: host.docker.internal:7890
      https_proxy: host.docker.internal:7890
    env_file:
      - .env
networks:
  biiboom:
