version: "3.3"
services:
  biiboom_etl:
    build: .
    container_name: biiboom-etl
    platform: linux/amd64
    restart: always
    networks:
      - biiboom
    environment:
      TZ: 'Asia/Shanghai'
      env: dev
#      pgsql_ip: host.docker.internal
networks:
  biiboom:
